# Generated by Django 3.2.4 on 2025-06-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcApp', '0002_auto_20241231_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Token', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
